<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/ems.Master" CodeBehind="frmModules.aspx.vb" Inherits="E_Management.frmModules" 
    title="Module Registration" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">
<table cellpadding=0 cellspacing=0 align="center">
	<tr>
					<td width="16"><IMG height="16" src="/images/top_lef.gif" width="16"></td>
					<td background="/images/top_mid.gif" height="16"><IMG height="16" src="/images/top_mid.gif" width="16"></td>
					<td width="24"><IMG height="16" src="/images/top_rig.gif" width="24"></td>
				</tr>
				<tr>
					<td width="16" background="/images/cen_lef.gif"><IMG height="11" src="/images/cen_lef.gif" width="16"></td>
					<td vAlign="top" bgColor="#ffffff">
<table align="center">
<tr><td colspan="2" align="center"  style="background: #5D7B9D; font-weight:bold; color:White">
    <asp:Label ID="Label2" runat="server" Font-Bold="True" Font-Size="Small" Text="Modules Registration"></asp:Label></td></tr>
<tr><td>
    <asp:Label ID="Label4" runat="server" Text="System"></asp:Label></td><td>
    <asp:DropDownList ID="DrpDwnSystem" runat="server" DataSourceID="SqlDataSource2"
        DataTextField="systemname" DataValueField="systemid" AutoPostBack="True">
    </asp:DropDownList><asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:E_Management.My.MySettings.hrmisConnectionString %>"
        SelectCommand="Sp_GetSystemsNids" SelectCommandType="StoredProcedure"></asp:SqlDataSource>
</td></tr>
<tr><td>
    <asp:Label ID="Label1" runat="server" Text="Module"></asp:Label></td><td>
        <asp:TextBox ID="TxtBoxModule" runat="server" MaxLength="50" Width="275px"></asp:TextBox></td></tr>
        <tr><td>
    <asp:Label ID="Label3" runat="server" Text="Description (Optional)"></asp:Label></td><td>
        <asp:TextBox ID="TxtBoxModuleDesc" runat="server" MaxLength="4000" TextMode="MultiLine" Width="280px"></asp:TextBox></td></tr>
<tr><td></td><td>
    <asp:Button ID="BtnSave" runat="server" Text="Add" /></td></tr>
    <tr><td id="Td1" runat="server" colspan="2">
        <asp:Label ID="LblMsg" runat="server" Font-Bold="True" Font-Size="Small"></asp:Label></td></tr>
        <tr><td colspan="2">
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" DataKeyNames="ModuleName"
        AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Width="394px">
        <Columns>
            <asp:BoundField DataField="systemname" HeaderText="System" SortExpression="systemname" />
            <asp:BoundField DataField="ModuleName" HeaderText="Module" SortExpression="ModuleName" />
            <asp:BoundField DataField="ModuleDesc" HeaderText="Description" SortExpression="ModuleDesc" />
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <EditRowStyle BackColor="#999999" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:E_Management.My.MySettings.hrmisConnectionString %>"
        SelectCommand="Sp_GetModules" SelectCommandType="StoredProcedure"
        deletecommand="Sp_DelModules" DeleteCommandType="StoredProcedure">
        <DeleteParameters>
            <asp:Parameter Name="ModuleName" Type="String" />
        </DeleteParameters>
        
    </asp:SqlDataSource></td></tr>
    </table>
     </td>
					<td width="24" background="/images/cen_rig.gif">
					<IMG height="11" src="/images/cen_rig.gif" width="24"></td>
				</tr>
				<tr>
					<td width="16" height="16"><IMG height="16" src="/images/bot_lef.gif" width="16"></td>
					<td background="/images/bot_mid.gif" height="16"><IMG height="16" src="/images/bot_mid.gif" width="16"></td>
					<td width="24" height="16"><IMG height="16" src="/images/bot_rig.gif" width="24"></td>
				</tr>
			</table>
</asp:Content>
