<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/ems.Master" CodeBehind="frmSetScreen.aspx.vb" Inherits="E_Management.frmSetScreen" 
    title="Set the Screens in a System" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">
    &nbsp;<table cellpadding=0 cellspacing=0 align="center">
	<tr>
					<td width="16"><IMG height="16" src="/images/top_lef.gif" width="16"></td>
					<td background="/images/top_mid.gif" height="16"><IMG height="16" src="/images/top_mid.gif" width="16"></td>
					<td width="24"><IMG height="16" src="/images/top_rig.gif" width="24"></td>
				</tr>
				<tr>
					<td width="16" background="/images/cen_lef.gif"><IMG height="11" src="/images/cen_lef.gif" width="16"></td>
					<td vAlign="top" bgColor="#ffffff">
<table align="center">
<tr><td colspan="2" align="center"  style="background: #5D7B9D; font-weight:bold; color:White">
    <asp:Label ID="Label2" runat="server" Font-Bold="True" Font-Size="Small" Text="Set Screens Path"></asp:Label></td></tr>
 <tr><td>
    <asp:Label ID="Label4" runat="server" Text="System"></asp:Label></td><td>
        <asp:DropDownList ID="DrpDwnSystem" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource2"
            DataTextField="systemname" DataValueField="systemid">
        </asp:DropDownList><asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:E_Management.My.MySettings.hrmisConnectionString %>"
            SelectCommand="Sp_GetSystemsNids" SelectCommandType="StoredProcedure"></asp:SqlDataSource>
    </td></tr> <tr><td>
    <asp:Label ID="Label5" runat="server" Text="Module"></asp:Label></td><td>
        <asp:DropDownList ID="DrpdwnModule" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource3"
            DataTextField="ModuleName" DataValueField="ModuleId">
        </asp:DropDownList><asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:E_Management.My.MySettings.hrmisConnectionString %>"
            SelectCommand="select * from tbl_modules where systemid = @systemid order by moduleid">
            <SelectParameters>
                <asp:ControlParameter ControlID="DrpDwnSystem" Name="systemid" PropertyName="SelectedValue" />
            </SelectParameters>
        </asp:SqlDataSource>
    </td></tr> <tr><td>
    <asp:Label ID="Label6" runat="server" Text="Screen Type"></asp:Label></td><td>
        <asp:DropDownList ID="DrpDwnScrtype" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource4"
            DataTextField="ScrType" DataValueField="scrtypeid">
        </asp:DropDownList><asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:E_Management.My.MySettings.hrmisConnectionString %>"
            SelectCommand="Sp_GetScrTypes" SelectCommandType="StoredProcedure"></asp:SqlDataSource>
    </td></tr>
     <tr><td>
    <asp:Label ID="Label8" runat="server" Text="Screen Name for menu"></asp:Label></td><td>
        <asp:TextBox ID="TxtBoxScreenName" runat="server" MaxLength="50" Width="275px"></asp:TextBox></td></tr>
<tr>
<td>
    <asp:Label ID="Label3" runat="server" Text="Screen path"></asp:Label></td><td>
    <asp:FileUpload ID="FileUpload1" runat="server" /></td></tr>
        <tr><td>
    <asp:Label ID="Label1" runat="server" Text="String to Add for file path"></asp:Label></td><td>
        <asp:TextBox ID="TxtBoxString" runat="server" MaxLength="50" Width="275px"></asp:TextBox></td></tr>
        <tr><td>
    <asp:Label ID="Label9" runat="server" Text="Screen Description"></asp:Label></td><td>
        <asp:TextBox ID="TxtBoxScrDesc" runat="server" MaxLength="50" Width="275px"></asp:TextBox></td></tr>
        <tr><td>
    <asp:Label ID="Label7" runat="server" Text="Panel Name"></asp:Label></td><td>
        <asp:TextBox ID="TxtBoxPanel" runat="server" MaxLength="50" Width="275px"></asp:TextBox></td></tr>
<tr><td></td><td>
    <asp:Button ID="BtnSave" runat="server" Text="Add" /></td></tr>
    <tr><td id="Td1" runat="server" colspan="2">
        <asp:Label ID="LblMsg" runat="server" Font-Bold="True" Font-Size="Small"></asp:Label></td></tr>
        <tr><td colspan="2">
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True"
        AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Width="394px">
        <Columns>
            <asp:BoundField DataField="Scrname" HeaderText="Screen" SortExpression="Scrname" />
            <asp:BoundField DataField="Pathdesc" HeaderText="Path" SortExpression="Pathdesc" />
            <asp:BoundField DataField="ScrDesc" HeaderText="Descritpion" SortExpression="ScrDesc" />
            <asp:BoundField DataField="Panelvisible" HeaderText="Panel visible" SortExpression="Panelvisible" />
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <EditRowStyle BackColor="#999999" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:E_Management.My.MySettings.hrmisConnectionString %>"
        SelectCommand="Sp_GetScreens" SelectCommandType="StoredProcedure"
        deletecommand="Sp_DelRoles" DeleteCommandType="StoredProcedure">
        <DeleteParameters>
            <asp:Parameter Name="Role" Type="String" />
        </DeleteParameters>
        
    </asp:SqlDataSource></td></tr>
    </table>
     </td>
					<td width="24" background="/images/cen_rig.gif">
					<IMG height="11" src="/images/cen_rig.gif" width="24"></td>
				</tr>
				<tr>
					<td width="16" height="16"><IMG height="16" src="/images/bot_lef.gif" width="16"></td>
					<td background="/images/bot_mid.gif" height="16"><IMG height="16" src="/images/bot_mid.gif" width="16"></td>
					<td width="24" height="16"><IMG height="16" src="/images/bot_rig.gif" width="24"></td>
				</tr>
			</table>
</asp:Content>
