<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/ems.Master" CodeBehind="frmIssueMould.aspx.vb" Inherits="E_Management.frmIssueMould" 
    title="Mould Issue Form" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">
<table cellpadding=0 cellspacing=0 align="center">
	<tr>
					<td width="16"><IMG height="16" src="/images/top_lef.gif" width="16"></td>
					<td background="/images/top_mid.gif" height="16" style="width: 480px"><IMG height="16" src="/images/top_mid.gif" width="16"></td>
					<td width="24"><IMG height="16" src="/images/top_rig.gif" width="24"></td>
				</tr>
				<tr>
					<td width="16" background="/images/cen_lef.gif"><IMG height="11" src="/images/cen_lef.gif" width="16"></td>
					<td vAlign="top" bgColor="#ffffff" style="width: 480px">
<table align="center">


        <tr><td colspan="2">
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True"
        AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Width="394px">
        <Columns>
            <asp:BoundField DataField="recno" HeaderText="recno" InsertVisible="False" ReadOnly="True"
                SortExpression="recno" />
            <asp:BoundField DataField="Product" HeaderText="Product" SortExpression="Product" />
            <asp:BoundField DataField="MouldNo" HeaderText="MouldNo" SortExpression="MouldNo" />
            <asp:BoundField DataField="PressMC" HeaderText="PressMC" SortExpression="PressMC" />
            <asp:BoundField DataField="expdate" HeaderText="expdate" SortExpression="expdate" />
            <asp:BoundField DataField="requestedby" HeaderText="requestedby" SortExpression="requestedby" />
             <asp:TemplateField HeaderText="Issue Mould">
                <EditItemTemplate>
                    <asp:CheckBox ID="CheckBox1" runat="server" />
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:CheckBox ID="CheckBox1" runat="server" />
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <EditRowStyle BackColor="#999999" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MMaintenanceConnectionString %>"
        SelectCommand="Sp_GetMouldsRequested" SelectCommandType="StoredProcedure"
        deletecommand="Sp_DelMoulds" DeleteCommandType="StoredProcedure">
        <DeleteParameters>
            <asp:Parameter Name="Product" Type="String" />
            <asp:Parameter Name="MouldNo" Type="String" />
        </DeleteParameters>
        
    </asp:SqlDataSource></td></tr>
    <tr><td></td><td>
    <asp:Button ID="BtnSave" runat="server" Text="Save" /></td></tr>
    <tr><td id="Td1" runat="server" colspan="2">
        <asp:Label ID="LblMsg" runat="server" Font-Bold="True" Font-Size="Small"></asp:Label></td></tr>
    </table>
    </td>
					<td width="24" background="/images/cen_rig.gif">
					<IMG height="11" src="/images/cen_rig.gif" width="24"></td>
				</tr>
				<tr>
					<td width="16" height="16"><IMG height="16" src="/images/bot_lef.gif" width="16"></td>
					<td background="/images/bot_mid.gif" height="16" style="width: 480px"><IMG height="16" src="/images/bot_mid.gif" width="16"></td>
					<td width="24" height="16"><IMG height="16" src="/images/bot_rig.gif" width="24"></td>
				</tr>
			</table>
</asp:Content>
