'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class FiringMAchineMAsterEdit
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents Panel1 As System.Web.UI.WebControls.Panel
    Protected WithEvents Label6 As System.Web.UI.WebControls.Label
    Protected WithEvents dept_ddl As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator4 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label7 As System.Web.UI.WebControls.Label
    Protected WithEvents mcno_ddl As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator5 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label8 As System.Web.UI.WebControls.Label
    Protected WithEvents mcname As System.Web.UI.WebControls.Label
    Protected WithEvents Label9 As System.Web.UI.WebControls.Label
    Protected WithEvents mcdesc As System.Web.UI.WebControls.Label
    Protected WithEvents mcreg As System.Web.UI.WebControls.Label
    Protected WithEvents zoneid As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents temperature As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label
    Protected WithEvents spec As System.Web.UI.WebControls.TextBox
    Protected WithEvents R7 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents addtogrid_btn As System.Web.UI.WebControls.Button
    Protected WithEvents R6 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents R9 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource5 As System.Web.UI.WebControls.SqlDataSource
End Class
