'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class FiringMcMaster
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents dept_ddl As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label14 As System.Web.UI.WebControls.Label
    Protected WithEvents mcno As System.Web.UI.WebControls.TextBox
    Protected WithEvents R2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents mcname As System.Web.UI.WebControls.TextBox
    Protected WithEvents R3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label15 As System.Web.UI.WebControls.Label
    Protected WithEvents mcdesc As System.Web.UI.WebControls.TextBox
    Protected WithEvents R4 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents smsrb As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents zoneid As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents temperature As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents R6 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label
    Protected WithEvents spec As System.Web.UI.WebControls.TextBox
    Protected WithEvents R7 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents R9 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents addtogrid_btn As System.Web.UI.WebControls.Button
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents SAVEET As System.Web.UI.WebControls.Button
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource5 As System.Web.UI.WebControls.SqlDataSource
End Class
