'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ZoneFailureReportSelection
    Protected WithEvents Label26 As System.Web.UI.WebControls.Label
    Protected WithEvents txtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator11 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RequiredFieldValidator12 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ccefrom As AjaxControlToolkit.CalendarExtender
    Protected WithEvents cceto As AjaxControlToolkit.CalendarExtender
    Protected WithEvents lbldeptr As System.Web.UI.WebControls.Label
    Protected WithEvents ddldeptr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblsectr As System.Web.UI.WebControls.Label
    Protected WithEvents mcnoddl As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents showrepZFR As System.Web.UI.WebControls.Button
    Protected WithEvents selsectreport As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlsect As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDesig As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlsecdept As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
End Class
