<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="EditRequestMould.aspx.vb" Inherits="E_Management.EditRequestMould"  MasterPageFile="~/ems.Master" Title="Edit Mould Request" %>

<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">
<table cellpadding="0" cellspacing="0" align="center">
	<tr>
					<td width="16"><IMG height="16" src="/images/top_lef.gif" width="16"></td>
					<td background="/images/top_mid.gif" height="16"><img  alt=""  height="16" src="/images/top_mid.gif" width="16" /></td>
					<td width="24"><img  alt=""  height="16" src="/images/top_rig.gif" width="24" /></td>
				</tr>
				<tr>
					<td width="16" background="/images/cen_lef.gif"><img  alt=""  height="11" src="/images/cen_lef.gif" width="16" /></td>
					<td valign="top" bgcolor="#ffffff">





<table>
<tr>
    <td colspan="1" style="background-color: #5d7b9d; text-align: center">
        <asp:ImageButton ID="ImageButton1" runat="server" Height="32px" ImageUrl="~/MMForms/images/back.jpg"
            Width="39px" /></td>
    <td colspan="2" style="background-color: #5d7b9d; text-align: center"><asp:Label id="Label7" runat="server" Font-Bold="True" Font-Size="Small" Text="Mould Request Details" ForeColor="White"></asp:Label></td>
</tr>

<tr>
<td style="background-color: beige"><asp:Label id="Label6" runat="server" Text="Department"></asp:Label></td><td><asp:DropDownList id="CMBDepartment" runat="server" Width="200px" AutoPostBack="True">
            </asp:DropDownList>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="CMBDepartment"
        ErrorMessage="Please Select Department" InitialValue="-Select-"></asp:RequiredFieldValidator></td>
</tr>

<tr>
    <td colspan="2">
    <asp:GridView id="GridView1" runat="server" ForeColor="#333333" AutoGenerateDeleteButton="True" GridLines="None" DataSourceID="SqlDataSource1" CellPadding="4" AutoGenerateColumns="False" AllowSorting="True" AllowPaging="True" OnSelectedIndexChanged="SelectEvent" DataKeyNames="RecNo">
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333"  />
                <Columns>
                    <asp:CommandField ShowSelectButton="True" SelectText="IssueMould" />
                    <asp:BoundField DataField="RecNo" HeaderText="RecNo" InsertVisible="False" ReadOnly="True"
                        SortExpression="RecNo" />
                    <asp:BoundField DataField="Product" HeaderText="Product" SortExpression="Product" />
                    <asp:BoundField DataField="MouldName" HeaderText="MouldName" SortExpression="MouldName" />
                    <asp:BoundField DataField="PressMC" HeaderText="PressMC" SortExpression="PressMC" />
                    <asp:BoundField DataField="DateNeeded" HeaderText="DateNeeded" ReadOnly="True" SortExpression="DateNeeded" />
                    <asp:BoundField DataField="Requestedby" HeaderText="Requestedby" SortExpression="Requestedby" />
                    <asp:BoundField DataField="RequestedOn" HeaderText="RequestedOn" ReadOnly="True"
                        SortExpression="RequestedOn" />
                        
                </Columns>
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White"  />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center"  />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333"  />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White"  />
                <EditRowStyle BackColor="#999999"  />
                <AlternatingRowStyle BackColor="White" ForeColor="#284775"  />
            </asp:GridView><asp:SqlDataSource id="SqlDataSource1" runat="server" DeleteCommand="Delete From MouldRequest Where RecNo=@RecNo" SelectCommand="SELECT     RecNo, Product, MouldName, PressMC, Convert(varchar(10),Expdate,103) as DateNeeded, Requestedby, Convert(varchar(10),RequestDate,103) as RequestedOn&#13;&#10;FROM         MouldRequest Where FGID=@FGID and Status='R'  Order By ExpDate" ConnectionString="<%$ ConnectionStrings:MMaintenanceConnectionString2 %>">
                <SelectParameters>
                    <asp:SessionParameter DefaultValue="21" Name="FGID" SessionField="fgid"  />
                </SelectParameters>
                <DeleteParameters>
                    <asp:Parameter Name="RecNo"  />
                </DeleteParameters>
            </asp:SqlDataSource>
    </td>
</tr>

</table>


                    </td>
					<td width="24" background="/images/cen_rig.gif">
					<img height="11" src="/images/cen_rig.gif" width="24" alt="" /></td>
				</tr>
				<tr>
					<td width="16" height="16"><img height="16"  alt="" src="/images/bot_lef.gif" width="16" /></td>
					<td background="/images/bot_mid.gif" height="16"><img  alt="" height="16" src="/images/bot_mid.gif" width="16" /></td>
					<td width="24" height="16"><img alt="" height="16" src="/images/bot_rig.gif" width="24" /></td>
				</tr>
			</table>
</asp:Content>